services:
  - type: web
    name: dashboard-ppsa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
